import React,{useMemo,useRef,useState} from 'react'
import type {ModuleId} from '../../app/types'
import {exportBIMJson,loadBIMModel,saveBIMModel,type BIMElement,type SmartStructBIMModel} from '../../engineering/bim/model'
import {BIM_LIBRARY,addLibraryItemToModel} from '../../engineering/bim/library'
import {downloadIFC} from '../../engineering/bim/ifcExport'
import {importIFCText,saveImportedIFC,type IFCImportSummary} from '../../engineering/bim/ifcImport'

const typePT:Record<string,string>={beam:'Vigas',column:'Pilares',slab:'Lajes',isolated_footing:'Sapatas',strip_footing:'Sapatas contínuas',raft_foundation:'Ensoleiramento',pile:'Estacas',wall:'Paredes',lsf_member:'LSF',pipe:'Tubagens',manhole:'Caixas de visita',road_element:'Elementos exteriores',furniture:'Mobiliário/Objetos',plumbing_fixture:'Equipamentos sanitários',masonry_unit:'Unidades de alvenaria',door:'Portas',window:'Janelas',material:'Materiais/Equipamentos'}
const fmt=(n:any,d=2)=>typeof n==='number'?n.toFixed(d):String(n??'—')
const BIM_HANDOFF_KEY='smartstruct:bim-calculation-handoff'
function targetModule(e:BIMElement):ModuleId|null{if(e.type==='beam')return 'beams';if(e.type==='column')return 'columns';if(e.type==='slab')return 'slabs';if(['isolated_footing','strip_footing','raft_foundation','pile'].includes(e.type))return 'foundations';return null}
function handoffElement(e:BIMElement){localStorage.setItem(BIM_HANDOFF_KEY,JSON.stringify({elementId:e.id,type:e.type,name:e.name,geometry:e.geometry,material:e.material,properties:e.properties,calculation:e.calculation,at:new Date().toISOString()}))}

export default function BIMModelPage({onOpen}:{onOpen?:(id:ModuleId)=>void}){
 const[tick,setTick]=useState(0),[importInfo,setImportInfo]=useState<IFCImportSummary|null>(null),fileRef=useRef<HTMLInputElement>(null)
 const[show,setShow]=useState<'all'|'structure'|'foundations'|'slabs'|'architecture'|'furniture'|'sanitary'>('all'),[rot,setRot]=useState(35),[zoom,setZoom]=useState(1),[selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<'model'|'library'>('model'),[query,setQuery]=useState('')
 const model=useMemo(()=>loadBIMModel(),[tick])
 const elements=useMemo(()=>!model?[]:model.elements.filter(e=>show==='all'||(show==='foundations'?['isolated_footing','strip_footing','raft_foundation','pile'].includes(e.type):show==='slabs'?e.type==='slab':show==='architecture'?['wall','masonry_unit','door','window'].includes(e.type):show==='furniture'?['furniture','road_element','material'].includes(e.type):show==='sanitary'?['plumbing_fixture','pipe','manhole'].includes(e.type):['beam','column','wall'].includes(e.type))),[model,show])
 const counts=useMemo(()=>model?Object.entries(model.elements.reduce<Record<string,number>>((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{})):[],[model])
 const lib=useMemo(()=>{const q=query.trim().toLowerCase();return q?BIM_LIBRARY.filter(i=>`${i.name} ${i.category} ${i.tags.join(' ')}`.toLowerCase().includes(q)):BIM_LIBRARY},[query])
 const commit=(m:SmartStructBIMModel)=>{saveBIMModel(m);setTick(x=>x+1)}
 const insert=(id:string)=>{let m=loadBIMModel();if(!m){alert('Crie primeiro um modelo em Modelo de Edifício ou importe um IFC.');return}const item=BIM_LIBRARY.find(x=>x.id===id);if(!item)return;m=addLibraryItemToModel(m,item);commit(m);setMode('model');setSelected(m.elements[m.elements.length-1].id)}
 const updateSelected=(patch:Record<string,number>)=>{if(!model||!selected)return;const els=model.elements.map(e=>{if(e.id!==selected)return e;const geometry={...e.geometry,...patch};const props={...e.properties};if(e.type==='column'){
   const b=Number(geometry.b||.3),h=Number(geometry.h||.3),cx=Number(geometry.x||0)+b/2,cy=Number(geometry.y||0)+h/2;geometry.axisX=cx;geometry.axisY=cy
   const feet=model.elements.filter(x=>x.type==='isolated_footing');let nearest:BIMElement|undefined,dist=Infinity
   for(const f of feet){const fx=Number(f.geometry.axisX??(Number(f.geometry.x||0)+Number(f.geometry.width||0)/2)),fy=Number(f.geometry.axisY??(Number(f.geometry.y||0)+Number(f.geometry.depth||0)/2)),d=Math.hypot(cx-fx,cy-fy);if(d<dist){dist=d;nearest=f}}
   props.foundationAxisStatus=dist<.005?'Centrado com sapata':`Excêntrico ${dist.toFixed(3)} m`;if(nearest){props.nearestFooting=nearest.id;props.offsetToFootingX_m=cx-Number(nearest.geometry.axisX??0);props.offsetToFootingY_m=cy-Number(nearest.geometry.axisY??0)}
  }return{...e,geometry,properties:props}});commit({...model,elements:els})}
 const duplicate=()=>{if(!model||!selected)return;const src=model.elements.find(e=>e.id===selected);if(!src)return;const n=model.elements.length+1,copy={...src,id:`${src.id}-COPY-${n}`,name:`${src.name} cópia`,geometry:{...src.geometry,x:Number(src.geometry.x||0)+.5,y:Number(src.geometry.y||0)+.5},properties:{...src.properties,duplicatedFrom:src.id}};commit({...model,elements:[...model.elements,copy]});setSelected(copy.id)}
 const remove=()=>{if(!model||!selected)return;commit({...model,elements:model.elements.filter(e=>e.id!==selected)});setSelected(null)}
 const selectedEl=model?.elements.find(e=>e.id===selected)||null
 return <div className="module-page bim-page"><div className="module-head"><div><h2>Modelo BIM · Editor Multidisciplinar</h2><p>Composição 3D do projeto com biblioteca, colocação/movimento de objetos, estrutura, arquitetura, instalações e interoperabilidade IFC/openBIM.</p></div><div className="bim-actions"><input ref={fileRef} type="file" accept=".ifc,.ifczip" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=importIFCText(await f.text());saveImportedIFC(r);setImportInfo(r);setTick(x=>x+1)}catch(err){alert(err instanceof Error?err.message:'Não foi possível importar o IFC.')}finally{e.target.value=''}}}/><button onClick={()=>setTick(x=>x+1)}>Atualizar</button><button onClick={()=>fileRef.current?.click()}>Importar IFC</button>{model&&<><button onClick={()=>exportBIMJson(model)}>BIM JSON</button><button className="primary" onClick={()=>downloadIFC(model)}>Exportar IFC</button></>}</div></div>
 <div className="tabs-row"><button className={mode==='model'?'active':''} onClick={()=>setMode('model')}>Modelo 3D</button><button className={mode==='library'?'active':''} onClick={()=>setMode('library')}>Biblioteca BIM</button></div>
 {importInfo&&<section className="panel bim-import-summary"><h3>Importação IFC / openBIM</h3><p><b>{importInfo.recognized}</b> elementos importados · esquema <b>{importInfo.sourceSchema}</b>.</p>{importInfo.warnings.map((w,i)=><p className="note" key={i}>{w}</p>)}</section>}
 {mode==='library'?<section className="panel"><div className="bim-lib-head"><div><h3>Biblioteca BIM alargada</h3><p className="note">Estrutura, fundações, alvenarias, envolvente, coberturas, drenagem, portas/janelas, escadas, cozinha, sanitários, mobiliário e exterior.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar pilar, sapata, janela, escada, cozinha, piscina…"/></div><div className="bim-library-grid">{lib.map(i=><article key={i.id} className="bim-library-card"><ElementGlyph type={i.type}/><div><small>{i.category}</small><h4>{i.name}</h4><p>{i.description}</p><code>{Object.entries(i.geometry).filter(([,v])=>typeof v==='number'||typeof v==='string').slice(0,4).map(([k,v])=>`${k}=${v}`).join(' · ')}</code></div><button className="primary" onClick={()=>insert(i.id)}>Inserir e posicionar</button></article>)}</div></section>:!model?<section className="panel"><h3>Ainda não existe modelo BIM</h3><p>Abra <b>Modelo de Edifício</b> e use <b>Atualizar modelo BIM</b>, ou importe um ficheiro IFC.</p></section>:<>
 <div className="result-grid"><div className="metric"><span>Elementos</span><b>{model.elements.length}</b></div><div className="metric"><span>Níveis</span><b>{new Set(model.elements.map(e=>e.level).filter(Boolean)).size}</b></div><div className="metric"><span>Biblioteca</span><b>{BIM_LIBRARY.length}</b></div><div className="metric"><span>Zoom</span><b>{Math.round(zoom*100)}%</b></div></div>
 <section className="panel bim-view-panel v116"><div className="bim-view-head"><div><h3>Visualizador / Editor BIM 3D</h3><small>Arraste horizontalmente para rodar; roda do rato ou botões para zoom. Selecione um objeto para o mover.</small></div><div className="bim-filter"><select value={show} onChange={e=>setShow(e.target.value as any)}><option value="all">Todos</option><option value="structure">Estrutura</option><option value="slabs">Lajes</option><option value="foundations">Fundações</option><option value="architecture">Arquitetura/Alvenaria</option><option value="furniture">Mobiliário/Exterior</option><option value="sanitary">Instalações</option></select><button onClick={()=>setRot(r=>r-15)}>↶</button><button onClick={()=>setRot(r=>r+15)}>↷</button><button onClick={()=>setZoom(z=>Math.max(.55,z-.1))}>−</button><button onClick={()=>setZoom(z=>Math.min(2.4,z+.1))}>+</button><button onClick={()=>{setRot(35);setZoom(1)}}>Enquadrar</button></div></div><BIMSvg elements={elements} rotation={rot} zoom={zoom} selected={selected} onSelect={setSelected} onRotate={setRot} onZoom={setZoom}/><div className="bim-legend"><span><i className="lg-column"/> Pilares</span><span><i className="lg-beam"/> Vigas</span><span><i className="lg-slab"/> Lajes</span><span><i className="lg-foot"/> Fundações</span></div></section>
 <div className="bim-editor-grid"><section className="panel"><h3>Inventário BIM</h3><div className="bim-inventory">{counts.map(([t,n])=><div key={t}><span>{typePT[t]||t}</span><b>{n}</b></div>)}</div></section><section className="panel"><h3>Objeto selecionado · posição</h3>{selectedEl?<SelectedEditor e={selectedEl} onChange={updateSelected} onDuplicate={duplicate} onDelete={remove}/>:<p className="note">Selecione um elemento no modelo 3D ou na tabela. Depois pode definir X, Y, Z e rotação para o colocar na vivenda/prédio.</p>}</section></div>
 <section className="panel"><h3>Objetos e propriedades</h3><div className="bim-object-table"><div className="bim-object-row head"><b>ID</b><b>Tipo</b><b>Nível</b><b>Material</b><b>Geometria principal</b><b>Estado</b></div>{model.elements.slice(0,140).map(e=><ObjectRow key={e.id} e={e} selected={selected===e.id} onSelect={()=>setSelected(e.id)} onOpen={onOpen}/>)}</div></section>
 </>}</div>
}
function SelectedEditor({e,onChange,onDuplicate,onDelete}:{e:BIMElement;onChange:(p:Record<string,number>)=>void;onDuplicate:()=>void;onDelete:()=>void}){const g=e.geometry;const num=(k:string)=>Number(g[k]||0);const step=.25;return <div className="bim-selected-editor"><b>{e.name}</b><span>{typePT[e.type]||e.type} · {e.level||'Sem nível'} · {e.material?.name||'Material não definido'}</span><div className="bim-position-grid"><label>X (m)<input type="number" step={step} value={num('x')} onChange={x=>onChange({x:Number(x.target.value)})}/></label><label>Y (m)<input type="number" step={step} value={num('y')} onChange={x=>onChange({y:Number(x.target.value)})}/></label><label>Z (m)<input type="number" step={step} value={num('z')} onChange={x=>onChange({z:Number(x.target.value)})}/></label><label>Rotação (°)<input type="number" step={15} value={num('rotation')} onChange={x=>onChange({rotation:Number(x.target.value)})}/></label></div><div className="bim-nudge"><button onClick={()=>onChange({x:num('x')-step})}>← X</button><button onClick={()=>onChange({x:num('x')+step})}>X →</button><button onClick={()=>onChange({y:num('y')-step})}>← Y</button><button onClick={()=>onChange({y:num('y')+step})}>Y →</button><button onClick={()=>onChange({z:num('z')-step})}>↓ Z</button><button onClick={()=>onChange({z:num('z')+step})}>Z ↑</button></div><small>{String(e.properties.foundationAxisStatus||'Snap manual: grelha 0,25 m. Elementos estruturais deslocados devem ser reverificados.')}</small><div className="bim-actions"><button onClick={onDuplicate}>Duplicar</button><button onClick={onDelete}>Apagar</button></div></div>}
function ElementGlyph({type}:{type:string}){return <div className={`bim-glyph ${type}`}><span/><i/></div>}
function ObjectRow({e,selected,onSelect,onOpen}:{e:BIMElement;selected:boolean;onSelect:()=>void;onOpen?:(id:ModuleId)=>void}){const g=e.geometry;const dims=e.type==='column'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='beam'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='slab'?`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.thickness)} m`:`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.height)} m`;const target=targetModule(e);return <div className={`bim-object-row${selected?' selected':''}`} onClick={onSelect}><span>{e.id}</span><span>{typePT[e.type]||e.type}</span><span>{e.level||'—'}</span><span>{e.material?.name||'—'}</span><span>{dims}</span><span>{e.calculation?.status==='preliminary'?'Pré-dimensionado':e.calculation?.status==='calculated'?'Calculado':'A verificar'}{target&&<button className="bim-calc-link" onClick={ev=>{ev.stopPropagation();handoffElement(e);onOpen?.(target)}}>Abrir cálculo</button>}</span></div>}

type P={x:number;y:number}
function BIMSvg({elements,rotation,zoom,selected,onSelect,onRotate,onZoom}:{elements:BIMElement[];rotation:number;zoom:number;selected:string|null;onSelect:(id:string)=>void;onRotate:(v:number)=>void;onZoom:(v:number)=>void}){
 const drag=useRef<{x:number;r:number}|null>(null)
 let maxX=1,maxY=1,maxZ=1,minZ=0;elements.forEach(e=>{const g=e.geometry,x=Number(g.x||0),y=Number(g.y||0),z=Number(g.z||0);let w=Number(g.width||.3),d=Number(g.depth||.3),h=Number(g.height||g.thickness||.3);if(e.type==='column'){w=Number(g.b||.3);d=Number(g.h||.3);h=Number(g.length||3)}else if(e.type==='beam'){const L=Number(g.length||1);w=g.axis==='Y'?Number(g.b||.25):L;d=g.axis==='Y'?L:Number(g.b||.25);h=Number(g.h||.45)}else if(e.type==='pile'){w=Number(g.width||.6);d=Number(g.depth||.6);h=Number(g.height||10)}maxX=Math.max(maxX,x+w);maxY=Math.max(maxY,y+d);maxZ=Math.max(maxZ,z+h);minZ=Math.min(minZ,z)})
 const W=1100,H=690,span=Math.max(maxX,maxY,1),base=Math.min(60,760/span,460/Math.max(maxZ-minZ,1)),scale=base*zoom,cx=maxX/2,cy=maxY/2,a=rotation*Math.PI/180
 const project=(x:number,y:number,z:number):P=>{const dx=x-cx,dy=y-cy,X=dx*Math.cos(a)-dy*Math.sin(a),Y=dx*Math.sin(a)+dy*Math.cos(a);return{x:W/2+(X-Y)*scale*.64,y:H/2+95-(z-(minZ+maxZ)/2)*scale-(X+Y)*scale*.24}}
 const box=(e:BIMElement)=>{const g=e.geometry,x=+g.x!||0,y=+g.y!||0,z=+g.z!||0;let w=+g.width!||.3,d=+g.depth!||.3,h=+g.height!||.3;if(e.type==='column'){w=+g.b!||.3;d=+g.h!||.3;h=+g.length!||3}else if(e.type==='beam'){const L=+g.length!||1;w=g.axis==='Y'?(+g.b!||.25):L;d=g.axis==='Y'?L:(+g.b!||.25);h=+g.h!||.45}else if(e.type==='slab'){w=+g.width!||1;d=+g.depth!||1;h=+g.thickness!||.18}else if(e.type==='wall'){w=+g.width!||4;d=+g.depth!||.25;h=+g.height!||3}else if(e.type==='pile'){w=+g.width!||.6;d=+g.depth!||.6;h=+g.height!||10}
 const p000=project(x,y,z),p100=project(x+w,y,z),p110=project(x+w,y+d,z),p010=project(x,y+d,z),p001=project(x,y,z+h),p101=project(x+w,y,z+h),p111=project(x+w,y+d,z+h),p011=project(x,y+d,z+h),pts=(aa:P[])=>aa.map(p=>`${p.x},${p.y}`).join(' '),cls=`bim-solid ${e.type}${selected===e.id?' true':''}`
 return <g key={e.id} className={cls} onClick={()=>onSelect(e.id)}><polygon points={pts([p000,p100,p101,p001])} className="face front"/><polygon points={pts([p100,p110,p111,p101])} className="face side"/><polygon points={pts([p001,p101,p111,p011])} className="face top"/><polyline points={pts([p000,p100,p110,p010,p000,p001,p101,p111,p011,p001])} className="edges"/></g>}
 const ordered=[...elements].sort((a,b)=>(+(a.geometry.x||0)+ +(a.geometry.y||0)+ +(a.geometry.z||0))-(+(b.geometry.x||0)+ +(b.geometry.y||0)+ +(b.geometry.z||0))),ground=[project(-1,-1,0),project(maxX+1,-1,0),project(maxX+1,maxY+1,0),project(-1,maxY+1,0)]
 return <svg viewBox={`0 0 ${W} ${H}`} className="bim-svg enhanced v116" onWheel={e=>{e.preventDefault();onZoom(Math.max(.55,Math.min(2.4,zoom+(e.deltaY<0?.08:-.08))))}} onPointerDown={e=>{drag.current={x:e.clientX,r:rotation};(e.currentTarget as SVGSVGElement).setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)onRotate(drag.current.r+(e.clientX-drag.current.x)*.35)}} onPointerUp={()=>{drag.current=null}}><defs><pattern id="grid116" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" className="bim-grid-line"/></pattern></defs><rect width={W} height={H} fill="url(#grid116)"/><polygon points={ground.map(p=>`${p.x},${p.y}`).join(' ')} className="bim-ground"/><g>{ordered.map(box)}</g><Axis3D project={project}/><text x="24" y="34" className="bim-svg-title">SmartStruct BIM · editor 3D · rotação {rotation.toFixed(0)}° · zoom {Math.round(zoom*100)}%</text></svg>
}
function Axis3D({project}:{project:(x:number,y:number,z:number)=>P}){const o=project(0,0,0),x=project(1.4,0,0),y=project(0,1.4,0),z=project(0,0,1.4);return <g className="bim-axis"><line x1={o.x} y1={o.y} x2={x.x} y2={x.y}/><line x1={o.x} y1={o.y} x2={y.x} y2={y.y}/><line x1={o.x} y1={o.y} x2={z.x} y2={z.y}/><text x={x.x} y={x.y}>X</text><text x={y.x} y={y.y}>Y</text><text x={z.x} y={z.y}>Z</text></g>}
