import React,{useMemo,useRef,useState} from 'react'
import type {ModuleId} from '../../app/types'
import {exportBIMJson,loadBIMModel,saveBIMModel,type BIMElement} from '../../engineering/bim/model'
import {BIM_LIBRARY,addLibraryItemToModel} from '../../engineering/bim/library'
import {downloadIFC} from '../../engineering/bim/ifcExport'
import {importIFCText,saveImportedIFC,type IFCImportSummary} from '../../engineering/bim/ifcImport'

const typePT:Record<string,string>={beam:'Vigas',column:'Pilares',slab:'Lajes',isolated_footing:'Sapatas',strip_footing:'Sapatas contínuas',raft_foundation:'Ensoleiramento',pile:'Estacas',wall:'Paredes',lsf_member:'LSF',pipe:'Tubagens',manhole:'Caixas de visita',road_element:'Elementos viários',furniture:'Mobiliário',plumbing_fixture:'Equipamentos sanitários',masonry_unit:'Unidades de alvenaria',door:'Portas',window:'Janelas',material:'Materiais'}
const fmt=(n:any,d=2)=>typeof n==='number'?n.toFixed(d):String(n??'—')
const BIM_HANDOFF_KEY='smartstruct:bim-calculation-handoff'
function targetModule(e:BIMElement):ModuleId|null{if(e.type==='beam')return 'beams';if(e.type==='column')return 'columns';if(e.type==='slab')return 'slabs';if(['isolated_footing','strip_footing','raft_foundation','pile'].includes(e.type))return 'foundations';return null}
function handoffElement(e:BIMElement){localStorage.setItem(BIM_HANDOFF_KEY,JSON.stringify({elementId:e.id,type:e.type,name:e.name,geometry:e.geometry,material:e.material,properties:e.properties,calculation:e.calculation,at:new Date().toISOString()}))}

export default function BIMModelPage({onOpen}:{onOpen?:(id:ModuleId)=>void}){
 const[tick,setTick]=useState(0),[importInfo,setImportInfo]=useState<IFCImportSummary|null>(null),fileRef=useRef<HTMLInputElement>(null)
 const[show,setShow]=useState<'all'|'structure'|'foundations'|'slabs'|'architecture'|'furniture'|'sanitary'>('all'),[rot,setRot]=useState(0),[selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<'model'|'library'>('model'),[query,setQuery]=useState('')
 const model=useMemo(()=>loadBIMModel(),[tick])
 const elements=useMemo(()=>!model?[]:model.elements.filter(e=>show==='all'||(show==='foundations'?['isolated_footing','strip_footing','raft_foundation','pile'].includes(e.type):show==='slabs'?e.type==='slab':show==='architecture'?['wall','masonry_unit','door','window'].includes(e.type):show==='furniture'?e.type==='furniture':show==='sanitary'?e.type==='plumbing_fixture':['beam','column','wall'].includes(e.type))),[model,show])
 const counts=useMemo(()=>model?Object.entries(model.elements.reduce<Record<string,number>>((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{})):[],[model])
 const lib=useMemo(()=>{const q=query.trim().toLowerCase();return q?BIM_LIBRARY.filter(i=>`${i.name} ${i.category} ${i.tags.join(' ')}`.toLowerCase().includes(q)):BIM_LIBRARY},[query])
 const insert=(id:string)=>{let m=loadBIMModel();if(!m){alert('Crie primeiro um modelo em Modelo de Edifício ou importe um IFC.');return}const item=BIM_LIBRARY.find(x=>x.id===id);if(!item)return;m=addLibraryItemToModel(m,item);saveBIMModel(m);setTick(x=>x+1);setMode('model');setSelected(m.elements[m.elements.length-1].id)}
 return <div className="module-page bim-page"><div className="module-head"><div><h2>Modelo BIM · Biblioteca Multidisciplinar</h2><p>Modelo 3D informacional com estrutura, arquitetura, mobiliário, equipamentos sanitários, materiais e interoperabilidade IFC/openBIM.</p></div><div className="bim-actions"><input ref={fileRef} type="file" accept=".ifc,.ifczip" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=importIFCText(await f.text());saveImportedIFC(r);setImportInfo(r);setTick(x=>x+1)}catch(err){alert(err instanceof Error?err.message:'Não foi possível importar o IFC.')}finally{e.target.value=''}}}/><button onClick={()=>setTick(x=>x+1)}>Atualizar</button><button onClick={()=>fileRef.current?.click()}>Importar IFC</button>{model&&<><button onClick={()=>exportBIMJson(model)}>BIM JSON</button><button className="primary" onClick={()=>downloadIFC(model)}>Exportar IFC</button></>}</div></div>
 <div className="tabs-row"><button className={mode==='model'?'active':''} onClick={()=>setMode('model')}>Modelo 3D</button><button className={mode==='library'?'active':''} onClick={()=>setMode('library')}>Biblioteca BIM</button></div>
 {importInfo&&<section className="panel bim-import-summary"><h3>Importação IFC / openBIM</h3><p><b>{importInfo.recognized}</b> elementos importados · esquema <b>{importInfo.sourceSchema}</b>.</p>{importInfo.warnings.map((w,i)=><p className="note" key={i}>{w}</p>)}</section>}
 {mode==='library'?<section className="panel"><div className="bim-lib-head"><div><h3>Biblioteca BIM de elementos e materiais</h3><p className="note">Estrutura, alvenarias, portas/janelas, mobiliário, torneiras e equipamentos sanitários. Os objetos são paramétricos e podem ser coordenados/exportados em IFC.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar pilar, sapata, tijolo, torneira, sofá…"/></div><div className="bim-library-grid">{lib.map(i=><article key={i.id} className="bim-library-card"><ElementGlyph type={i.type}/><div><small>{i.category}</small><h4>{i.name}</h4><p>{i.description}</p><code>{Object.entries(i.geometry).filter(([,v])=>typeof v==='number'||typeof v==='string').slice(0,4).map(([k,v])=>`${k}=${v}`).join(' · ')}</code></div><button className="primary" onClick={()=>insert(i.id)}>Inserir no modelo</button></article>)}</div></section>:!model?<section className="panel"><h3>Ainda não existe modelo BIM</h3><p>Abra <b>Modelo de Edifício</b> e use <b>Atualizar modelo BIM</b>, ou importe um ficheiro IFC.</p></section>:<>
 <div className="result-grid"><div className="metric"><span>Elementos</span><b>{model.elements.length}</b></div><div className="metric"><span>Níveis</span><b>{new Set(model.elements.map(e=>e.level).filter(Boolean)).size}</b></div><div className="metric"><span>Biblioteca</span><b>{BIM_LIBRARY.length}</b></div><div className="metric"><span>Atualizado</span><b>{new Date(model.updatedAt).toLocaleDateString('pt-PT')}</b></div></div>
 <section className="panel bim-view-panel"><div className="bim-view-head"><div><h3>Visualizador BIM 3D</h3><small>Volumes, níveis, fundações e seleção de objetos em vista isométrica.</small></div><div className="bim-filter"><select value={show} onChange={e=>setShow(e.target.value as any)}><option value="all">Todos</option><option value="structure">Estrutura</option><option value="slabs">Lajes</option><option value="foundations">Fundações</option><option value="architecture">Arquitetura/Alvenaria</option><option value="furniture">Mobiliário</option><option value="sanitary">Equip. sanitários</option></select><button onClick={()=>setRot(r=>(r+1)%4)}>Rodar 90°</button></div></div><BIMSvg elements={elements} rotation={rot} selected={selected} onSelect={setSelected}/><div className="bim-legend"><span><i className="lg-column"/> Pilares</span><span><i className="lg-beam"/> Vigas</span><span><i className="lg-slab"/> Lajes</span><span><i className="lg-foot"/> Fundações</span></div></section>
 <div className="work-grid"><section className="panel"><h3>Inventário BIM</h3><div className="bim-inventory">{counts.map(([t,n])=><div key={t}><span>{typePT[t]||t}</span><b>{n}</b></div>)}</div></section><section className="panel"><h3>Objeto selecionado</h3>{model.elements.find(e=>e.id===selected)?<SelectedCard e={model.elements.find(e=>e.id===selected)!}/>:<p className="note">Selecione um elemento no modelo 3D ou na tabela.</p>}</section></div>
 <section className="panel"><h3>Objetos e propriedades</h3><div className="bim-object-table"><div className="bim-object-row head"><b>ID</b><b>Tipo</b><b>Nível</b><b>Material</b><b>Geometria principal</b><b>Estado</b></div>{model.elements.slice(0,100).map(e=><ObjectRow key={e.id} e={e} selected={selected===e.id} onSelect={()=>setSelected(e.id)} onOpen={onOpen}/>)}</div></section>
 </>}</div>
}
function SelectedCard({e}:{e:BIMElement}){return <div className="bim-selected-card"><b>{e.name}</b><span>{typePT[e.type]||e.type} · {e.level||'Sem nível'}</span><span>{e.material?.name||'Material não definido'}</span><small>{Object.entries(e.geometry).slice(0,8).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small></div>}
function ElementGlyph({type}:{type:string}){return <div className={`bim-glyph ${type}`}><span/><i/></div>}
function ObjectRow({e,selected,onSelect,onOpen}:{e:BIMElement;selected:boolean;onSelect:()=>void;onOpen?:(id:ModuleId)=>void}){const g=e.geometry;const dims=e.type==='column'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='beam'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='slab'?`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.thickness)} m`:`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.height)} m`;const target=targetModule(e);return <div className={`bim-object-row${selected?' selected':''}`} onClick={onSelect}><span>{e.id}</span><span>{typePT[e.type]||e.type}</span><span>{e.level||'—'}</span><span>{e.material?.name||'—'}</span><span>{dims}</span><span>{e.calculation?.status==='preliminary'?'Pré-dimensionado':e.calculation?.status==='calculated'?'Calculado':'A verificar'}{target&&<button className="bim-calc-link" onClick={ev=>{ev.stopPropagation();handoffElement(e);onOpen?.(target)}}>Abrir cálculo</button>}</span></div>}

type P={x:number;y:number}
function BIMSvg({elements,rotation,selected,onSelect}:{elements:BIMElement[],rotation:number;selected:string|null;onSelect:(id:string)=>void}){
 let maxX=1,maxY=1,maxZ=1,minZ=0;elements.forEach(e=>{const g=e.geometry,x=Number(g.x||0),y=Number(g.y||0),z=Number(g.z||0);let w=Number(g.width||.3),d=Number(g.depth||.3),h=Number(g.height||g.thickness||.3);if(e.type==='column'){w=Number(g.b||.3);d=Number(g.h||.3);h=Number(g.length||3)}else if(e.type==='beam'){const L=Number(g.length||1);w=g.axis==='Y'?Number(g.b||.25):L;d=g.axis==='Y'?L:Number(g.b||.25);h=Number(g.h||.45)}else if(e.type==='pile'){w=Number(g.width||.6);d=Number(g.depth||.6);h=Number(g.height||10)}maxX=Math.max(maxX,x+w);maxY=Math.max(maxY,y+d);maxZ=Math.max(maxZ,z+h);minZ=Math.min(minZ,z)})
 const W=960,H=590,span=Math.max(maxX,maxY,1),scale=Math.min(52,650/span,390/Math.max(maxZ-minZ,1));
 const project=(x:number,y:number,z:number):P=>{let X=x,Y=y;if(rotation===1){X=y;Y=maxX-x}else if(rotation===2){X=maxX-x;Y=maxY-y}else if(rotation===3){X=maxY-y;Y=x}return{x:W/2+(X-Y)*scale*.72,y:H-75-(z-minZ)*scale-(X+Y)*scale*.29}}
 const box=(e:BIMElement)=>{const g=e.geometry,x=+g.x!||0,y=+g.y!||0,z=+g.z!||0;let w=+g.width!||.3,d=+g.depth!||.3,h=+g.height!||.3;if(e.type==='column'){w=+g.b!||.3;d=+g.h!||.3;h=+g.length!||3}else if(e.type==='beam'){const L=+g.length!||1;w=g.axis==='Y'?(+g.b!||.25):L;d=g.axis==='Y'?L:(+g.b!||.25);h=+g.h!||.45}else if(e.type==='slab'){w=+g.width!||1;d=+g.depth!||1;h=+g.thickness!||.18}else if(e.type==='wall'){w=+g.width!||4;d=+g.depth!||.25;h=+g.height!||3}else if(e.type==='pile'){w=+g.width!||.6;d=+g.depth!||.6;h=+g.height!||10}
 const p000=project(x,y,z),p100=project(x+w,y,z),p110=project(x+w,y+d,z),p010=project(x,y+d,z),p001=project(x,y,z+h),p101=project(x+w,y,z+h),p111=project(x+w,y+d,z+h),p011=project(x,y+d,z+h)
 const pts=(a:P[])=>a.map(p=>`${p.x},${p.y}`).join(' '),sel=selected===e.id?' true':'',cls=`bim-solid ${e.type}${sel}`
 return <g key={e.id} className={cls} onClick={()=>onSelect(e.id)}><polygon points={pts([p000,p100,p101,p001])} className="face front"/><polygon points={pts([p100,p110,p111,p101])} className="face side"/><polygon points={pts([p001,p101,p111,p011])} className="face top"/><polyline points={pts([p000,p100,p110,p010,p000,p001,p101,p111,p011,p001])} className="edges"/></g>}
 const ordered=[...elements].sort((a,b)=>(+(a.geometry.x||0)+ +(a.geometry.y||0)+ +(a.geometry.z||0))-(+(b.geometry.x||0)+ +(b.geometry.y||0)+ +(b.geometry.z||0)))
 const ground=[project(0,0,0),project(maxX+1,0,0),project(maxX+1,maxY+1,0),project(0,maxY+1,0)]
 return <svg viewBox={`0 0 ${W} ${H}`} className="bim-svg enhanced"><defs><pattern id="grid113" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" className="bim-grid-line"/></pattern></defs><rect width={W} height={H} fill="url(#grid113)"/><polygon points={ground.map(p=>`${p.x},${p.y}`).join(' ')} className="bim-ground"/><g>{ordered.map(box)}</g><Axis3D project={project}/><text x="22" y="30" className="bim-svg-title">SmartStruct BIM · modelo 3D informacional</text></svg>
}
function Axis3D({project}:{project:(x:number,y:number,z:number)=>P}){const o=project(0,0,0),x=project(1.4,0,0),y=project(0,1.4,0),z=project(0,0,1.4);return <g className="bim-axis"><line x1={o.x} y1={o.y} x2={x.x} y2={x.y}/><line x1={o.x} y1={o.y} x2={y.x} y2={y.y}/><line x1={o.x} y1={o.y} x2={z.x} y2={z.y}/><text x={x.x} y={x.y}>X</text><text x={y.x} y={y.y}>Y</text><text x={z.x} y={z.y}>Z</text></g>}
