import React,{useMemo,useState} from 'react'
import {buildConceptualBuildingBIM,saveBIMModel} from '../../engineering/bim/model'
import {solveFrame2D,type FrameModel} from '../../engineering/core/frame2d'
import {isolatedFootingPro} from '../foundationsPro/FoundationsSolver'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function makeFrame(floors:number,bays:number,bay:number,storey:number,q:number,H:number):FrameModel{
 const ns:any[]=[],es:any[]=[];let eid=1
 for(let j=0;j<=floors;j++)for(let i=0;i<=bays;i++){const id=j*(bays+1)+i+1;ns.push({id,x:i*bay,y:j*storey,...(j===0?{fixX:true,fixY:true,fixR:true}:{}),...(j===floors&&i===bays?{Fx:H*1000}:{})})}
 for(let j=0;j<floors;j++)for(let i=0;i<=bays;i++){const a=j*(bays+1)+i+1,b=(j+1)*(bays+1)+i+1;es.push({id:eid++,a,b,E:30e9,A:.12,I:.0016})}
 for(let j=1;j<=floors;j++)for(let i=0;i<bays;i++){const a=j*(bays+1)+i+1,b=a+1;es.push({id:eid++,a,b,E:30e9,A:.15,I:.003,qy:-q*1000})}
 return{nodes:ns,elements:es}
}
function ceil5(x:number){return Math.ceil(x/0.05)*0.05}
function autoColumn(N:number,M:number){
 const demand=Math.max(.25,Math.sqrt(Math.max(N,1)/12000)+Math.sqrt(Math.max(Math.abs(M),1)/8000))
 const b=Math.min(.60,Math.max(.25,ceil5(demand))),h=Math.min(.70,Math.max(.30,ceil5(demand*1.15)))
 return{b,h,label:`${Math.round(b*100)}×${Math.round(h*100)} cm`}
}
function autoBeam(L:number,q:number,Mend:number){
 const h=Math.min(.80,Math.max(.35,ceil5(L/12))),b=Math.min(.40,Math.max(.25,ceil5(h*.45)))
 const Med=Math.max(q*L*L/8,Math.abs(Mend))
 return{b,h,Med,label:`${Math.round(b*100)}×${Math.round(h*100)} cm`}
}
function autoFooting(N:number,H:number,Mm:number,qadm:number,cb:number,ch:number){
 let B=Math.max(1.2,ceil5(Math.sqrt(Math.max(N,1)/Math.max(qadm*.80,1)))),L=B,h=.50,r:any=null
 for(let k=0;k<24;k++){r=isolatedFootingPro({N,Hx:H,Hy:0,Mx:Math.abs(Mm),My:0,B,L,h,cb,cl:ch,cover:.05,qAllow:qadm,mu:.5,fck:30,fyk:500,phi:12});if(r.ok&&r.bearingUtil<=.9)break;if(r.bearingUtil>.9||r.qmin<0){B+=.1;L+=.1}else h+=.05}
 return{B,L,h,r}
}
export default function BuildingModelPage(){
 const[buildingType,setBuildingType]=useState<'villa'|'building'>('villa')
 const[roofType,setRoofType]=useState('4 águas'),[roofAngle,setRoofAngle]=useState(30),[roofFinish,setRoofFinish]=useState('Telha cerâmica'),[exploded,setExploded]=useState(false)
 const[floors,setFloors]=useState(2),[bays,setBays]=useState(2),[bay,setBay]=useState(5),[storey,setStorey]=useState(3),[depth,setDepth]=useState(6),[q,setQ]=useState(12),[wind,setWind]=useState(25),[qadm,setQadm]=useState(250),[bimSaved,setBimSaved]=useState('')
 const nf=Math.max(1,Math.min(buildingType==='villa'?3:6,Math.round(floors))),nb=Math.max(1,Math.min(5,Math.round(bays))),model=useMemo(()=>makeFrame(nf,nb,bay,storey,q,wind),[nf,nb,bay,storey,q,wind])
 const solved=useMemo(()=>{try{return{r:solveFrame2D(model),err:''}}catch(e){return{r:null,err:e instanceof Error?e.message:String(e)}}},[model])
 const design=useMemo(()=>{if(!solved.r)return null
  const bases=model.nodes.filter(n=>n.y===0)
  const foundations=bases.map((n,k)=>{const i=model.nodes.findIndex(x=>x.id===n.id),Rx=solved.r!.reactions[3*i]/1000,Ry=solved.r!.reactions[3*i+1]/1000,Mm=solved.r!.reactions[3*i+2]/1000,N=Math.max(0,Ry),col=autoColumn(N,Mm),foot=autoFooting(N,Math.abs(Rx),Mm,qadm,col.b,col.h);return{id:n.id,index:k+1,Rx,Ry,M:Mm,col,foot}})
  const beams=solved.r.endForces.filter((e:any)=>{const el=model.elements.find(x=>x.id===e.elementId)!;const a=model.nodes.find(n=>n.id===el.a)!,b=model.nodes.find(n=>n.id===el.b)!;return Math.abs(a.y-b.y)<1e-6}).map((e:any)=>{const el=model.elements.find(x=>x.id===e.elementId)!,sz=autoBeam(e.L,q,Math.max(Math.abs(e.M1),Math.abs(e.M2))/1000);return{id:e.elementId,...sz}})
  return{foundations,beams}
 },[solved.r,model,q,qadm])
 const maxDisp=solved.r?Math.max(...model.nodes.map((_,i)=>Math.hypot(solved.r!.displacements[3*i],solved.r!.displacements[3*i+1]))):0
 const updateBIM=()=>{if(!design)return;const bim=buildConceptualBuildingBIM({floors:nf,bays:nb,bay,storey,depth,columns:design.foundations.map(x=>({index:x.index,N:x.Ry,M:x.M,b:x.col.b,h:x.col.h,footB:x.foot.B,footL:x.foot.L,footH:x.foot.h,qmax:x.foot.r.qmax,util:x.foot.r.bearingUtil})),beams:design.beams.map(x=>({id:x.id,b:x.b,h:x.h,Med:x.Med}))});saveBIMModel(bim);setBimSaved(new Date().toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'}))}
 return <div className="module-page"><div className="module-head"><div><h2>Modelo de Edifício · AUTO</h2><p>Geometria → análise global → pré-dimensionamento automático → modelo BIM estrutural conceptual.</p></div>{design&&<div className="bim-actions"><button className="primary" onClick={updateBIM}>Atualizar modelo BIM</button>{bimSaved&&<small>Guardado às {bimSaved}</small>}</div>}</div>
 <div className="work-grid"><section className="panel"><h3>Edifício</h3><div className="tabs-row"><button className={buildingType==='villa'?'active':''} onClick={()=>{setBuildingType('villa');setFloors(f=>Math.min(f,3))}}>Vivenda · até 3 pisos</button><button className={buildingType==='building'?'active':''} onClick={()=>setBuildingType('building')}>Prédio</button></div><p className="note">A opção Vivenda limita automaticamente o modelo a 3 pisos. Prédio mantém o gerador atual para edifícios de maior desenvolvimento.</p><div className="form-grid"><F l="Pisos" v={floors} s={setFloors}/><F l="Vãos" v={bays} s={setBays}/><F l="Largura vão" u="m" v={bay} s={setBay}/><F l="Pé-direito" u="m" v={storey} s={setStorey}/><F l="Profundidade edifício" u="m" v={depth} s={setDepth}/><F l="q vigas" u="kN/m" v={q} s={setQ}/><F l="Ação horizontal topo" u="kN" v={wind} s={setWind}/><F l="qadm terreno" u="kPa" v={qadm} s={setQadm}/></div>{buildingType==='villa'&&<><h3>Cobertura</h3><div className="form-grid"><label>Tipo<select value={roofType} onChange={e=>setRoofType(e.target.value)}><option>1 água</option><option>2 águas</option><option>4 águas</option><option>Mansarda</option><option>Em L</option><option>Plana</option><option>Verde</option></select></label><F l="Inclinação" u="°" v={roofAngle} s={setRoofAngle}/><label>Revestimento<select value={roofFinish} onChange={e=>setRoofFinish(e.target.value)}><option>Telha cerâmica</option><option>Telha de betão</option><option>Chapa metálica</option><option>Painel sandwich</option><option>Zinco</option><option>Membrana PVC/TPO</option></select></label></div><div className="tabs-row"><button className={!exploded?'active':''} onClick={()=>setExploded(false)}>Vista 3D</button><button className={exploded?'active':''} onClick={()=>setExploded(true)}>3D explodido</button></div><p className="note">Inclui cumeeiras, rincões, larós, beirados, rufos, caleiras, tubos de queda, ralos, pendentes, isolamento, impermeabilização e drenagem.</p></>}</section><section className="panel"><h3>Modelo gerado</h3><Building3DSvg floors={nf} bays={nb} bay={bay} storey={storey} depth={depth} buildingType={buildingType} roofType={roofType} roofAngle={roofAngle} roofFinish={roofFinish} exploded={exploded}/>{solved.err&&<div className="solver-error">{solved.err}</div>}</section></div>
 {solved.r&&design&&<><div className="result-grid"><M t="Nós" v={`${model.nodes.length}`}/><M t="Barras" v={`${model.elements.length}`}/><M t="Vigas dimensionadas" v={`${design.beams.length}`}/><M t="Fundações" v={`${design.foundations.length}`}/><M t="Desloc. máx." v={`${(maxDisp*1000).toFixed(2)} mm`}/></div>
 <section className="panel"><h3>Pilares de base · secção automática</h3><div className="member-table">{design.foundations.map(x=><div key={x.id}><b>P{x.index}</b><span>N {x.Ry.toFixed(1)} kN</span><span>M {x.M.toFixed(1)} kN·m</span><span>Secção {x.col.label}</span></div>)}</div></section>
 <section className="panel"><h3>Vigas · secção automática</h3><div className="member-table">{design.beams.map(x=><div key={x.id}><b>Viga {x.id}</b><span>Secção {x.label}</span><span>M referência {x.Med.toFixed(1)} kN·m</span></div>)}</div></section>
 <section className="panel"><h3>Sapatas · otimização individual</h3><div className="member-table">{design.foundations.map(x=><div key={x.id}><b>F{x.index}</b><span>{x.foot.B.toFixed(2)}×{x.foot.L.toFixed(2)}×{x.foot.h.toFixed(2)} m</span><span>qmax {x.foot.r.qmax.toFixed(1)} kPa</span><span>Util. {(100*x.foot.r.bearingUtil).toFixed(0)}%</span><span>FS desl. {x.foot.r.slideFS.toFixed(2)}</span><span>{x.foot.r.ok?'OK':'REVER'}</span></div>)}</div></section>
 <section className="panel"><h3>Cadeia de engenharia + BIM</h3><div className="flow-line"><b>Edifício</b><span>→</span><b>Solver</b><span>→</span><b>Esforços</b><span>→</span><b>Secções</b><span>→</span><b>Fundações</b><span>→</span><b>BIM 3D</b></div><p className="note">AUTO significa pré-dimensionamento automático, não projeto regulamentar final. As regras de seleção de secção são heurísticas de engenharia; a análise matricial fornece os esforços, mas EC2/EC7, combinações, 2.ª ordem global, fissuração, punçoamento e geotecnia devem ser verificados.</p></section></>}</div>}
function Building3DSvg({floors,bays,bay,storey,depth,buildingType,roofType,roofAngle,roofFinish,exploded}:{floors:number;bays:number;bay:number;storey:number;depth:number;buildingType:'villa'|'building';roofType:string;roofAngle:number;roofFinish:string;exploded:boolean}){
 const W=900,H=590,spanX=Math.max(bays*bay,1),spanY=Math.max(depth,1),spanZ=Math.max(floors*storey+(buildingType==='villa'?Math.tan(roofAngle*Math.PI/180)*depth*.5:0),1),scale=Math.min(58,620/Math.max(spanX,spanY),390/spanZ),cx=spanX/2,cy=spanY/2,cz=floors*storey/2;
 const P=(x:number,y:number,z:number)=>{const X=x-cx,Y=y-cy;return{x:W/2+(X-Y)*scale*.70,y:H/2+65-(z-cz)*scale-(X+Y)*scale*.26}}
 const line=(a:any,b:any,cls:string,k:string)=><line key={k} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={cls}/>
 const items:any[]=[]
 for(let fl=0;fl<floors;fl++)for(let r=0;r<2;r++)for(let x=0;x<=bays;x++)items.push(line(P(x*bay,r*depth,fl*storey),P(x*bay,r*depth,(fl+1)*storey),'building3d-column',`c${fl}-${r}-${x}`))
 for(let fl=1;fl<=floors;fl++){for(let r=0;r<2;r++)for(let x=0;x<bays;x++)items.push(line(P(x*bay,r*depth,fl*storey),P((x+1)*bay,r*depth,fl*storey),'building3d-beam',`bx${fl}-${r}-${x}`));for(let x=0;x<=bays;x++)items.push(line(P(x*bay,0,fl*storey),P(x*bay,depth,fl*storey),'building3d-beam',`by${fl}-${x}`))}
 const slabs=[] as any[];for(let fl=1;fl<=floors;fl++)for(let x=0;x<bays;x++){const ps=[P(x*bay,0,fl*storey),P((x+1)*bay,0,fl*storey),P((x+1)*bay,depth,fl*storey),P(x*bay,depth,fl*storey)];slabs.push(<polygon key={`s${fl}-${x}`} points={ps.map(q=>`${q.x},${q.y}`).join(' ')} className="building3d-slab"/>)}
 const roofZ=floors*storey+(exploded?1.4:0), roofBase=[P(0,0,roofZ),P(bays*bay,0,roofZ),P(bays*bay,depth,roofZ),P(0,depth,roofZ)], ridgeA=P(bays*bay*.18,depth*.5,roofZ+Math.tan(roofAngle*Math.PI/180)*depth*.5), ridgeB=P(bays*bay*.82,depth*.5,roofZ+Math.tan(roofAngle*Math.PI/180)*depth*.5);
 const roof=buildingType==='villa'?(roofType==='Plana'||roofType==='Verde'?<g><polygon points={roofBase.map(q=>`${q.x},${q.y}`).join(' ')} className="building3d-slab"/><line x1={roofBase[0].x} y1={roofBase[0].y} x2={roofBase[2].x} y2={roofBase[2].y} className="building3d-beam"/><text x={roofBase[0].x} y={roofBase[0].y-8}>ralos · pendentes · tubos de queda</text></g>:<g><polygon points={[roofBase[0],roofBase[1],ridgeB,ridgeA].map(q=>`${q.x},${q.y}`).join(' ')} className="building3d-slab"/><polygon points={[roofBase[3],roofBase[2],ridgeB,ridgeA].map(q=>`${q.x},${q.y}`).join(' ')} className="building3d-slab"/><line x1={ridgeA.x} y1={ridgeA.y} x2={ridgeB.x} y2={ridgeB.y} className="building3d-beam"/><text x={ridgeA.x} y={ridgeA.y-8}>cumeeira · caleiras · rufos</text></g>):null;
 const ground=[P(-1,-1,0),P(bays*bay+1,-1,0),P(bays*bay+1,depth+1,0),P(-1,depth+1,0)]
 return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg building-3d"><polygon points={ground.map(q=>`${q.x},${q.y}`).join(' ')} className="building3d-ground"/>{slabs}{items}{roof}<text x="20" y="25">{buildingType==='villa'?'Vivenda':'Prédio'} · modelo 3D paramétrico</text><text x="20" y="45" className="muted-svg">{floors} pisos · {bays} vãos · profundidade {depth.toFixed(1)} m · {roofType} {roofAngle}° · {roofFinish}{exploded?' · EXPLODIDO':''}</text></svg>
}